# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
20      - name: Install pipenv
21        run: |
22          python -m pip install --upgrade pipenv wheel
23      - id: cache-pipenv
24        uses: actions/cache@v1
25        with:
26          path: ~/.local/share/virtualenvs
27          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
28
29      - name: Install dependencies
30        if: steps.cache-pipenv.outputs.cache-hit != 'true'
31        run: |
32          pipenv install --deploy --dev
    - name: Test with pytest
      run: |
        pytest
